### ISSUE TITLE
speed comparisons

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdatar#1]
Thanks @Robinlovelace for mpadge/osmplotr#5 ! Comparison code now up on [osmdatar](https://github.com/osmdatar/osmdatar). The code of @hrbrmstr is definitely faster than `osmar` (see commit message, or do a simple `R CMD check` to time it yourself) ... the question is, is it fast enough? Simplest next step will be to `microbenchmark` the actual `XML->sp` conversion to get a better idea of speed. I'll get on to that shortly, then I guess I need to do a comparison with an equivalent C++ version so we've got a true idea about speeds. Once we know that, we can start constructing a package...

**Comment by Robinlovelace** [comment]
@mattwhittle91 may also be interested in this - he found it took ages to download 20 mph roads in the UK using osmplotr. Could be an interesting exercise to rerun the process using the overpass package for comparison. I recommend using RStudio's profvis package for identifying bottlenecks in code. (Update: mentioning @mwhittle91 properly now.)

**Comment by mpadge** [comment]
`microbenchmark` tests now part of the `readme` showing how much faster the `overpass` code is. The problem is the inherent inefficiency of loops in R regardless of how they're done. The bottlenecks in `osmar` are pretty easy to identify (it does an initial loop over each sp::Line to extract data, then an additional loop to convert all to sp::Lines -- this is very inefficient and slow). The bottlenecks in the code of **hrbrmstr** are of course the two `lapply` loops (in `process_osm_ways` and `osm_ways_to_spldf`). These are very neatly done, but still s-l-o-w for the amounts of data possible with `overpass`. We gotta find us a better way ...

**Comment by Robinlovelace** [comment]
Cool - thanks for this. Is it worth creating a script or perhaps even a vignette outlining some of these tests so we can track the improvement over time? I agree finding a better way would be good - imagine you're thinking C++. Any ideas @richardellison ?

**Comment by hrbrmstr** [comment]
I'll have some time this weekend to dig as well. I've been slammed (and
sick) since SFO, unfortunately.

**Comment by mpadge** [comment]
Thanks @Robinlovelace and @hrbrmstr ! I've run a C++ test using [libosmium](https://github.com/osmcode/libosmium) using slightly different data that should be roughly comparable. The result: 0.01-0.02s, compared with >1s for R. (Admittedly only extracting within C++; final conversion to `sp` data frames will add additional time.)

**The problem**: There is no way [libosmium](https://github.com/osmcode/libosmium) can be incorporated within an `R` package because it's way too big with too many dependencies.

**The lesson**: C++ is definitely going to be way superior to internal-`R`

**The task** (at least in my opinion): develop sufficiently lightweight `Rcpp` code (either by adapting [libosmium](https://github.com/osmcode/libosmium) or starting anew) that retains as much of the flexibility of [libosmium](https://github.com/osmcode/libosmium) as possible.

**Comment by Robinlovelace** [comment]
Thanks for doing the research - that sounds really promising. I note that packages such as [rgdal](https://cran.r-project.org/web/packages/rgdal/index.html) and [rgeos](https://cran.r-project.org/web/packages/rgeos/index.html) depend on large C libraries. So could the size issue not be bypassed by listing libosmium as a dependency?

**Comment by mpadge** [comment]
@Robinlovelace i've Rcpp-ed a very crude first go done for highways only, with speed results on the readme. It's currently likely much slower than what ought be possible because it's a poorly-programmed first cut on my part that depends on a loop in the R function, but even then it's obviously going to be a winner. (My comment about poor programming only pertains to the Rcpp::export and R bits; not the underlying C++ code, which is pretty polished.)

I'll clean up the Rcpp/R code a bit (and hopefully speed it up) soon, and then we can start talking about how to structure this as a package. Maybe one way would be for me to concentrate on the C++ side and you to concentrate on the R-front-end. We can discuss that a bit down the track.
