### ISSUE TITLE
replace boost dependency with rapidxml header

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdatar#4]

**Comment by jeroen** [comment]
Alternatively, you can simply add `LinkingTo: BH` in your `DESCRIPTION` because the `BH` package ships with `property_tree/xml_parser.hpp`.

**Comment by Robinlovelace** [comment]
With guidance from @jeroenooms I uninstalled boost from my system to test portability:

```
sudo apt-get purge libboost-all-dev 
sudo apt-get autoremove
```

Then tried the following:

``` r
devtools::install_github("osmdatar/osmdatar") # error
```

Then tried the following (after adding the **BH** link):

``` r
devtools::install_github("robinlovelace/osmdatar") # works
```

Full error message from 1st option:

```
devtools::install_github("osmdatar/osmdatar")
Downloading GitHub repo osmdatar/osmdatar@master
from URL https://api.github.com/repos/osmdatar/osmdatar/zipball/master
Installing osmdatar
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL '/tmp/RtmpAGPJnQ/devtools71b86445042/osmdatar-osmdatar-891d23c'  \
  --library='/home/robin/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘osmdatar’ ...
** libs
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -fprofile-arcs -ftest-coverage  -I"/home/robin/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -fprofile-arcs -ftest-coverage  -I"/home/robin/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c common.cpp -o common.o
In file included from common.cpp:2:0:
common.h:3:41: fatal error: boost/property_tree/ptree.hpp: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:141: recipe for target 'common.o' failed
make: *** [common.o] Error 1
ERROR: compilation failed for package ‘osmdatar’
* removing ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.3/osmdatar’
* restoring previous ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.3/osmdatar’
Error: Command failed (1)
```

**Comment by virgesmith** [comment]
Hi, I'm looking at replacing boost with rapidxml (I've got it working for get-points), and have to admit my domain knowledge is essentially zero, but would it be more efficient to have a single class loading all the xml rather than 3 separate ones that only load certain tags? Would also be nice to wrap whatever xml parser up in such a way the rest of the code is completely agnostic to it, so its easily changed in the future.  Also wondering what guarantees (if any) we have on the structure of the xml? Might be possible to load it faster if e.g. we know its a flat structure of nodes with (optional) tag child elements.

Also wondering what the rationale for removing boost::property_tree is? Is the compile-time dep on boost headers (assume this is what BH is) a problem? Note this is header-only code so there is no link-time dep.

Andrew

**Comment by mpadge** [comment]
Thanks for digging further @virgesmith. Some thoughts:

> would it be more efficient to have a single class loading all the xml rather than 3 separate ones that only load certain tags?

In short, I'm not sure, and likely some insight from @Robinlovelace and @hrbrmstr will help here. My potentially ill-conceived justification for present structure:
1. End-user of R package is likely to know what they want (either points, lines, or polygons), so a single query is likely only to involve one of those (and thus there ought not be an issue of efficiency because the three classes will never exist simultaneously).
2. The alternative of returning all data from a single query (points, lines, and polygons) may be ambiguous because polygons are represented as (closed) lines, so I'd suggest that the user really needs to state the desired form.
3. They do have distinctly different XML structures, particularly polygons which are potentially much more complicated and would make understanding the structure of a single class for the purpose of simple points or lines considerably more difficult.

On the other hand, having three classes do fairly similar jobs in a way that could potentially be covered by a single class is in principle rarely a grand idea and should be avoided where possible. Thoughts?

> Would also be nice to wrap whatever xml parser up in such a way the rest of the code is completely agnostic to it, so its easily changed in the future

That was my motivation for using [`boost::property_tree`](http://www.boost.org/doc/libs/1_62_0/doc/html/property_tree.html), because that's just a generic interface to any kind of tree-structured data, but it now seems necessary to change the interface to explicit [`rapidXML`](http://rapidxml.sourceforge.net/) at the expense of some flexibility. Nevertheless the XML structure of an `openstreetmap` document is very unlikely to change ([it will remain like this](https://wiki.openstreetmap.org/wiki/Elements), with [potential changes in the finer details](http://wiki.openstreetmap.org/wiki/OSM_XML#Certainties_and_Uncertainties) not affecting the functioning of [`rapidXML`](http://rapidxml.sourceforge.net/).

> Also wondering what guarantees (if any) we have on the structure of the xml? Might be possible to load it faster if e.g. we know its a flat structure of nodes with (optional) tag child elements.

That might be possible. It would very likely necessitate keeping the current three separate classes, but the actual hierarchy in each case is indeed fixed. I'll open an issue on that one ...

In the meantime, I'm currently trying to finish parsing OSM multipolygons, so it'd be great if you could keep going with the `boost`->`rapidXML` conversion for points and lines and then we can converge to finish polygons together.

thanks Andrew,
mark

**Comment by virgesmith** [comment]
Hmmmm... I've just done a fairly unscientific speed comparison for get-lines using the example data (2421 nodes) and the difference in load time is quite astounding:
boost ~ 40ms
rapidxml ~ 8ms

Seems like a compelling reason to switch to me!

**Comment by mpadge** [comment]
Awesome @virgesmith - difference no doubt from obviating the need to load boost libs. Exciting stuff!

**Comment by virgesmith** [comment]
Created a pull request with the rapidxml changes, think might be a tricky merge.

BTW, set<> requires uniqueness of the elements, so there's no need to worry about inserting duplicates. Thus no real need to check if the element exists unless overwriting is very expensive. find() is O(ln n) and insert is O(ln n + 1) (since it first needs to find the right place to insert). So, checking first then inserting is a O(2ln n + 1) operation.

**Comment by mpadge** [comment]
Merged. Thanks a million @virgesmith, that's awesome work, and much simpler than I was fearing all along. You've done me an enormous service! For future ref: speed-up is documented [here](https://github.com/osmdatar/osmdatar/pull/9)

**Comment by virgesmith** [comment]
Any clue as to what exactly is broken. Check Package works for me locally
Any way to see the content of 
/home/travis/build/osmdatar/osmdatar/osmdatar.Rcheck/00install.out’?

**Comment by mpadge** [comment]
Check works locally for me too. The output is in `R CMD check out logs` on travis:

```
common.cpp:9:44: error: invalid use of incomplete type 'const string {aka const struct std::basic_string<char>}'
/usr/include/c++/4.6/bits/stringfwd.h:61:11: error: declaration of 'const string {aka const struct std::basic_string<char>}'
```

It seems to come from the `const_cast`, but I can't figure out what the problem is. I'll try an lxc build ...

**Comment by virgesmith** [comment]
`#include <string>`
will fix it.

**Comment by mpadge** [comment]
Sure will - thanks @virgesmith

**Comment by mpadge** [comment]
Thanks @virgesmith for all of your help on this. I'm closing now. Latest commits are working towards consolidating a single class def. All `structs` and `typedefs` moved to `common.h`, and previous `std::vector <Node/Way>` all changed to `std::map <Node/Way>` - that's a great improvement thanks to you.

Just one question for the mo: Are the `clear()`s in the class constructors/destructors necessary?
